name: GTA Glitches Webhook

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ejecutar-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: node bot.js
